sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

services:
  - mysql

addons:
  apt:
    packages:
    - nginx

cache:
  directories:
  - $HOME/.drush/cache/download

before_install:
  - cp $TRAVIS_BUILD_DIR/.travis/php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
  - cp $TRAVIS_BUILD_DIR/.travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.0.0-rc3/drush.phar && chmod +x ~/drush.phar
  - php ~/drush.phar make $TRAVIS_BUILD_DIR/.travis/drupal.make.yml $HOME/www
  - php ~/drush.phar --root=$HOME/www --yes site-install --sites-subdir=8080.localhost --db-url=mysql://root:@127.0.0.1/localhost8080 testing

install:
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/key_value

script:
  - cd ~/www && php ./core/scripts/run-tests.sh --verbose --keep-results --color --concurrency 4 --php `which php` --sqlite /tmp/test.sqlite --url http://localhost:8080 --module key_value
